M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Thu 09 Nov 2023 04:27:47 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-09T16:27:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X3.05Y-3.5
X3.45Y-3.5
X3.9Y-3.5
X4.3Y-3.5
T2
X3.25Y-3.5
X4.1Y-3.5
T0
M30
